plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
    id "io.qameta.allure" version "3.0.1"
}

repositories {
    mavenCentral()
}

group = 'ru.example'
version = '1.0-SNAPSHOT'

dependencies {

    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.2.21")
    testImplementation("org.jetbrains.kotlin:kotlin-test:2.2.21")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.1")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.20.1")

    testImplementation("io.rest-assured:rest-assured:6.0.0")
    testImplementation("io.rest-assured:json-schema-validator:6.0.0")

    testImplementation ("com.codeborne:selenide-proxy:7.14.0")

    testImplementation("io.qameta.allure:allure-selenide:2.32.0")
    testImplementation("io.qameta.allure:allure-rest-assured:2.32.0")
    testImplementation 'io.qameta.allure:allure-junit5:2.32.0'

    testImplementation("ch.qos.logback:logback-classic:1.5.32")
    testImplementation("io.github.oshai:kotlin-logging-jvm:8.0.01")
    testImplementation("org.slf4j:slf4j-simple:2.0.9")


}

kotlin {
    jvmToolchain(21)
}

tasks.test {
    useJUnitPlatform()
    systemProperties["allure.results.directory"] = "build/allure-results"
    systemProperties["allure.report.directory"] = "build/allure-report"
    systemProperty("API_TOKEN", project.property("API_TOKEN") as String)
    testLogging {
        events("passed", "skipped", "failed", "standardOut", "standardError")
        showStandardStreams = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}

// Настройки очистки отчёта Allure
tasks.register("cleanAllureResults") {
    delete("build/allure-results")
}

tasks.named("test") {
    dependsOn("cleanAllureResults")
}

//sourceSets {
//    test {
//        kotlin.srcDirs("src/test/kotlin/pay/payment/tests")
//    }
//}